# Generated by Django 3.1.7 on 2021-03-09 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myRevendeurApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infoproduct',
            old_name='quantity',
            new_name='quantityInStock',
        ),
    ]
