# Generated by Django 3.1.7 on 2021-03-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myRevendeurApp', '0002_auto_20210309_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoproduct',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='infoproduct',
            name='sale',
            field=models.BooleanField(default=False),
        ),
    ]
